server:
  port: 8070

  servlet:
    encoding:
      force-response: true
#logging:
#  level:
#    root: info
#    org.springframework.web: trace



spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


local:
  file-upload-path: /Users/xuewenke/temp-file/doc-diff-server/upload/
  script: /Users/xuewenke/temp-file/doc-diff-server/script/
  temp: /Users/xuewenke/temp-file/doc-diff-server/temp/
  markdown: /Users/xuewenke/temp-file/doc-diff-server/process/markdown/
